package com.example.dynamodbtest.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Music")
public class Music {
    
    private String artist;
    private String songTitle;
    
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getArtist() {
        return artist;
    }

    @DynamoDBAttribute
    public String getSongTitle() {
        return songTitle;
    }
    
    public void setArtist(String artist) {
        this.artist = artist;
    }
    
    public void setSongTitle(String songTitle) {
        this.songTitle = songTitle;
    }
}
